"""Initial schema

Revision ID: 2551850d8650
Revises: 
Create Date: 2026-07-20 16:23:58.729005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2551850d8650'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='billing'
    )
    op.create_table('environments',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='common'
    )
    op.create_table('severity_levels',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    schema='common'
    )
    op.create_table('status_types',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    schema='common'
    )
    op.create_table('connector_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='connector'
    )
    op.create_table('datasource_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('supports_catalog', sa.Boolean(), nullable=True),
    sa.Column('supports_lineage', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='datasource'
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='identity'
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='identity'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='identity'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='marketplace'
    )
    op.create_table('traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('span_id', sa.String(length=128), nullable=True),
    sa.Column('parent_span_id', sa.String(length=128), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('operation_name', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id'),
    schema='monitoring'
    )
    op.create_table('provider_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='provider'
    )
    op.create_table('sdk_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('repository_url', sa.Text(), nullable=True),
    sa.Column('documentation_url', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sdk'
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_index(op.f('ix_system_api_keys_id'), 'api_keys', ['id'], unique=False, schema='system')
    op.create_index(op.f('ix_system_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False, schema='system')
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_index(op.f('ix_system_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='system')
    op.create_index(op.f('ix_system_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False, schema='system')
    op.create_table('billing_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_index(op.f('ix_system_billing_events_id'), 'billing_events', ['id'], unique=False, schema='system')
    op.create_index(op.f('ix_system_billing_events_metric'), 'billing_events', ['metric'], unique=False, schema='system')
    op.create_index(op.f('ix_system_billing_events_tenant_id'), 'billing_events', ['tenant_id'], unique=False, schema='system')
    op.create_table('system_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_name', sa.String(length=255), nullable=True),
    sa.Column('component_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_index(op.f('ix_system_system_health_component_name'), 'system_health', ['component_name'], unique=False, schema='system')
    op.create_table('owners',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ownership_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('entity_type', 'entity_id', 'user_id'),
    schema='governance'
    )
    op.create_table('role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['identity.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='identity'
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['identity.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('metadata_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lineage'
    )
    op.create_table('sdk_downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sdk_release_id', sa.UUID(), nullable=True),
    sa.Column('downloaded_by', sa.UUID(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_ip', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['downloaded_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['sdk_release_id'], ['sdk.sdk_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sdk'
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='search'
    )
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='search'
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['billing.plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['identity.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False, schema='billing')
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('publisher_tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['marketplace.categories.id'], ),
    sa.ForeignKeyConstraint(['publisher_tenant_id'], ['identity.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_items_item_type'), 'items', ['item_type'], unique=False, schema='marketplace')
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['identity.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='workspace'
    )
    op.create_index(op.f('ix_workspace_workspaces_tenant_id'), 'workspaces', ['tenant_id'], unique=False, schema='workspace')
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='agent'
    )
    op.create_index(op.f('ix_agent_agents_name'), 'agents', ['name'], unique=False, schema='agent')
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='agent'
    )
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tool_type', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('schema_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='agent'
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('latest_version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_prompt_templates_name'), 'prompt_templates', ['name'], unique=False, schema='ai')
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing.subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    schema='billing'
    )
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('license_key', sa.String(length=255), nullable=False),
    sa.Column('seat_limit', sa.Numeric(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing.subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_key'),
    schema='billing'
    )
    op.create_table('usage_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['identity.tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billing'
    )
    op.create_table('catalogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['identity.tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    op.create_table('connector_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connector_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connector_type_id'], ['connector.connector_types.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='connector'
    )
    op.create_table('context_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('ttl_hours', sa.Integer(), nullable=True),
    sa.Column('compression_strategy', sa.String(length=100), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='context'
    )
    op.create_table('context_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('retrieval_strategy', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='context'
    )
    op.create_table('datasources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('datasource_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['datasource_type_id'], ['datasource.datasource_types.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='datasource'
    )
    op.create_index(op.f('ix_datasource_datasources_workspace_id'), 'datasources', ['workspace_id'], unique=False, schema='datasource')
    op.create_table('business_glossaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_table('classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_table('installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('installed_by', sa.UUID(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['installed_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['marketplace.items.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='marketplace'
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('transport', sa.String(length=50), nullable=True),
    sa.Column('authentication_type', sa.String(length=50), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mcp'
    )
    op.create_table('memory_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('memory_type', sa.String(length=100), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='monitoring'
    )
    op.create_index(op.f('ix_monitoring_events_event_type'), 'events', ['event_type'], unique=False, schema='monitoring')
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=True),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='monitoring'
    )
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notification'
    )
    op.create_table('ontologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ontology'
    )
    op.create_table('plugins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('plugin_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='plugin'
    )
    op.create_index(op.f('ix_plugin_plugins_name'), 'plugins', ['name'], unique=False, schema='plugin')
    op.create_table('provider_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_type_id'], ['provider.provider_types.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='provider'
    )
    op.create_index(op.f('ix_provider_provider_configs_workspace_id'), 'provider_configs', ['workspace_id'], unique=False, schema='provider')
    op.create_table('quality_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_table('background_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduler'
    )
    op.create_index(op.f('ix_scheduler_background_tasks_status'), 'background_tasks', ['status'], unique=False, schema='scheduler')
    op.create_table('job_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduler'
    )
    op.create_table('secret_stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secrets'
    )
    op.create_table('configuration_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('flag_key', sa.String(length=200), nullable=False),
    sa.Column('flag_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('rollout_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_index(op.f('ix_system_feature_flags_flag_key'), 'feature_flags', ['flag_key'], unique=False, schema='system')
    op.create_table('maintenance_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maintenance_type', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('setting_key', sa.String(length=255), nullable=False),
    sa.Column('setting_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['identity.tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_index(op.f('ix_system_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=False, schema='system')
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='workspace'
    )
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent'
    )
    op.create_table('chat_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_config_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=True),
    sa.Column('supports_tools', sa.Boolean(), nullable=True),
    sa.Column('supports_vision', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_config_id'], ['provider.provider_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('embedding_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_config_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('supports_batch', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_config_id'], ['provider.provider_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['ai.prompt_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('reranker_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_config_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('max_documents', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_config_id'], ['provider.provider_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('catalog_databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.catalogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.datasources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('context_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['context.context_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='context'
    )
    op.create_table('glossary_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('glossary_id', sa.UUID(), nullable=True),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('steward_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['glossary_id'], ['governance.business_glossaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['steward_user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index(op.f('ix_governance_glossary_terms_term'), 'glossary_terms', ['term'], unique=False, schema='governance')
    op.create_table('tag_assignments',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['governance.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'entity_type', 'entity_id'),
    schema='governance'
    )
    op.create_table('lineage_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.datasources.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lineage'
    )
    op.create_index(op.f('ix_lineage_lineage_jobs_status'), 'lineage_jobs', ['status'], unique=False, schema='lineage')
    op.create_table('mcp_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['mcp.mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mcp'
    )
    op.create_table('memory_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['memory.memory_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index(op.f('ix_memory_memory_jobs_status'), 'memory_jobs', ['status'], unique=False, schema='memory')
    op.create_table('memory_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('importance_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('consolidation_interval', sa.String(length=50), nullable=True),
    sa.Column('expiration_strategy', sa.String(length=100), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['memory.memory_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['notification.channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notification'
    )
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ontology_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('concept_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology.ontologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ontology'
    )
    op.create_table('plugin_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plugin_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='plugin'
    )
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_definition_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['job_definition_id'], ['scheduler.job_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduler'
    )
    op.create_index(op.f('ix_scheduler_job_runs_status'), 'job_runs', ['status'], unique=False, schema='scheduler')
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_store_id', sa.UUID(), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('rotation_enabled', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['secret_store_id'], ['secrets.secret_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='secrets'
    )
    op.create_table('workflow_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent.agent_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='agent'
    )
    op.create_index(op.f('ix_agent_agent_runs_status'), 'agent_runs', ['status'], unique=False, schema='agent')
    op.create_table('agent_skills',
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent.agent_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['agent.skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_version_id', 'skill_id'),
    schema='agent'
    )
    op.create_table('agent_tools',
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent.agent_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['agent.tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_version_id', 'tool_id'),
    schema='agent'
    )
    op.create_table('model_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_model_id', sa.UUID(), nullable=True),
    sa.Column('embedding_model_id', sa.UUID(), nullable=True),
    sa.Column('input_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('output_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_model_id'], ['ai.chat_models.id'], ),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['ai.embedding_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('prompt_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider_config_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['ai.prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['provider_config_id'], ['provider.provider_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_prompt_executions_created_at'), 'prompt_executions', ['created_at'], unique=False, schema='ai')
    op.create_table('prompt_variables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=False),
    sa.Column('variable_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['ai.prompt_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('catalog_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['catalog.catalog_databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('lineage_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lineage_job_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('graph_hash', sa.String(length=128), nullable=True),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lineage_job_id'], ['lineage.lineage_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='lineage'
    )
    op.create_table('mcp_tool_permissions',
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['mcp.mcp_tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'role_id'),
    schema='mcp'
    )
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['notification.subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='notification'
    )
    op.create_table('concept_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_concept_id', sa.UUID(), nullable=True),
    sa.Column('target_concept_id', sa.UUID(), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_concept_id'], ['ontology.concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_concept_id'], ['ontology.concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ontology'
    )
    op.create_table('plugin_dependencies',
    sa.Column('plugin_version_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_plugin_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_plugin_version_id'], ['plugin.plugin_versions.id'], ),
    sa.ForeignKeyConstraint(['plugin_version_id'], ['plugin.plugin_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plugin_version_id', 'depends_on_plugin_version_id'),
    schema='plugin'
    )
    op.create_table('secret_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.secrets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secrets'
    )
    op.create_index(op.f('ix_secrets_secret_access_logs_accessed_at'), 'secret_access_logs', ['accessed_at'], unique=False, schema='secrets')
    op.create_table('workflow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow.workflow_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow.workflow_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    op.create_index(op.f('ix_workflow_workflow_runs_status'), 'workflow_runs', ['status'], unique=False, schema='workflow')
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('log_level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent.agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent'
    )
    op.create_table('catalog_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['catalog.catalog_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_catalog_tables_name'), 'catalog_tables', ['name'], unique=False, schema='catalog')
    op.create_table('catalog_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['catalog.catalog_schemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('context_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent.agent_runs.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['context.context_policies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['context.context_profiles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='context'
    )
    op.create_index(op.f('ix_context_context_sessions_agent_run_id'), 'context_sessions', ['agent_run_id'], unique=False, schema='context')
    op.create_table('mcp_tool_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent.agent_runs.id'], ),
    sa.ForeignKeyConstraint(['executed_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['mcp.mcp_tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mcp'
    )
    op.create_index(op.f('ix_mcp_mcp_tool_executions_executed_at'), 'mcp_tool_executions', ['executed_at'], unique=False, schema='mcp')
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('provider_config_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent.agent_runs.id'], ),
    sa.ForeignKeyConstraint(['provider_config_id'], ['provider.provider_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='monitoring'
    )
    op.create_index(op.f('ix_monitoring_llm_usage_model_name'), 'llm_usage', ['model_name'], unique=False, schema='monitoring')
    op.create_table('workflow_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['workflow.workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['workflow.workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow.workflow_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    op.create_table('workflow_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['workflow.workflow_nodes.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow.workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    op.create_table('catalog_columns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['catalog.catalog_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_catalog_columns_name'), 'catalog_columns', ['name'], unique=False, schema='catalog')
    op.create_table('quality_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['quality.quality_rules.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['catalog.catalog_tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_index(op.f('ix_quality_quality_checks_status'), 'quality_checks', ['status'], unique=False, schema='quality')
    op.create_table('quality_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('check_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['quality.quality_checks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_issues', schema='quality')
    op.drop_index(op.f('ix_quality_quality_checks_status'), table_name='quality_checks', schema='quality')
    op.drop_table('quality_checks', schema='quality')
    op.drop_index(op.f('ix_catalog_catalog_columns_name'), table_name='catalog_columns', schema='catalog')
    op.drop_table('catalog_columns', schema='catalog')
    op.drop_table('workflow_tasks', schema='workflow')
    op.drop_table('workflow_edges', schema='workflow')
    op.drop_index(op.f('ix_monitoring_llm_usage_model_name'), table_name='llm_usage', schema='monitoring')
    op.drop_table('llm_usage', schema='monitoring')
    op.drop_index(op.f('ix_mcp_mcp_tool_executions_executed_at'), table_name='mcp_tool_executions', schema='mcp')
    op.drop_table('mcp_tool_executions', schema='mcp')
    op.drop_index(op.f('ix_context_context_sessions_agent_run_id'), table_name='context_sessions', schema='context')
    op.drop_table('context_sessions', schema='context')
    op.drop_table('catalog_views', schema='catalog')
    op.drop_index(op.f('ix_catalog_catalog_tables_name'), table_name='catalog_tables', schema='catalog')
    op.drop_table('catalog_tables', schema='catalog')
    op.drop_table('agent_logs', schema='agent')
    op.drop_index(op.f('ix_workflow_workflow_runs_status'), table_name='workflow_runs', schema='workflow')
    op.drop_table('workflow_runs', schema='workflow')
    op.drop_table('workflow_nodes', schema='workflow')
    op.drop_index(op.f('ix_secrets_secret_access_logs_accessed_at'), table_name='secret_access_logs', schema='secrets')
    op.drop_table('secret_access_logs', schema='secrets')
    op.drop_table('plugin_dependencies', schema='plugin')
    op.drop_table('concept_relationships', schema='ontology')
    op.drop_table('deliveries', schema='notification')
    op.drop_table('mcp_tool_permissions', schema='mcp')
    op.drop_table('lineage_snapshots', schema='lineage')
    op.drop_table('catalog_schemas', schema='catalog')
    op.drop_table('prompt_variables', schema='ai')
    op.drop_index(op.f('ix_ai_prompt_executions_created_at'), table_name='prompt_executions', schema='ai')
    op.drop_table('prompt_executions', schema='ai')
    op.drop_table('model_pricing', schema='ai')
    op.drop_table('agent_tools', schema='agent')
    op.drop_table('agent_skills', schema='agent')
    op.drop_index(op.f('ix_agent_agent_runs_status'), table_name='agent_runs', schema='agent')
    op.drop_table('agent_runs', schema='agent')
    op.drop_table('workflow_versions', schema='workflow')
    op.drop_table('secrets', schema='secrets')
    op.drop_index(op.f('ix_scheduler_job_runs_status'), table_name='job_runs', schema='scheduler')
    op.drop_table('job_runs', schema='scheduler')
    op.drop_table('plugin_versions', schema='plugin')
    op.drop_table('concepts', schema='ontology')
    op.drop_table('subscriptions', schema='notification')
    op.drop_table('memory_policies', schema='memory')
    op.drop_index(op.f('ix_memory_memory_jobs_status'), table_name='memory_jobs', schema='memory')
    op.drop_table('memory_jobs', schema='memory')
    op.drop_table('mcp_tools', schema='mcp')
    op.drop_index(op.f('ix_lineage_lineage_jobs_status'), table_name='lineage_jobs', schema='lineage')
    op.drop_table('lineage_jobs', schema='lineage')
    op.drop_table('tag_assignments', schema='governance')
    op.drop_index(op.f('ix_governance_glossary_terms_term'), table_name='glossary_terms', schema='governance')
    op.drop_table('glossary_terms', schema='governance')
    op.drop_table('context_templates', schema='context')
    op.drop_table('catalog_databases', schema='catalog')
    op.drop_table('reranker_models', schema='ai')
    op.drop_table('prompt_versions', schema='ai')
    op.drop_table('embedding_models', schema='ai')
    op.drop_table('chat_models', schema='ai')
    op.drop_table('agent_versions', schema='agent')
    op.drop_table('projects', schema='workspace')
    op.drop_table('workflows', schema='workflow')
    op.drop_index(op.f('ix_system_system_settings_setting_key'), table_name='system_settings', schema='system')
    op.drop_table('system_settings', schema='system')
    op.drop_table('maintenance_windows', schema='system')
    op.drop_index(op.f('ix_system_feature_flags_flag_key'), table_name='feature_flags', schema='system')
    op.drop_table('feature_flags', schema='system')
    op.drop_table('configuration_profiles', schema='system')
    op.drop_table('secret_stores', schema='secrets')
    op.drop_table('job_definitions', schema='scheduler')
    op.drop_index(op.f('ix_scheduler_background_tasks_status'), table_name='background_tasks', schema='scheduler')
    op.drop_table('background_tasks', schema='scheduler')
    op.drop_table('quality_rules', schema='quality')
    op.drop_index(op.f('ix_provider_provider_configs_workspace_id'), table_name='provider_configs', schema='provider')
    op.drop_table('provider_configs', schema='provider')
    op.drop_index(op.f('ix_plugin_plugins_name'), table_name='plugins', schema='plugin')
    op.drop_table('plugins', schema='plugin')
    op.drop_table('ontologies', schema='ontology')
    op.drop_table('channels', schema='notification')
    op.drop_table('metrics', schema='monitoring')
    op.drop_index(op.f('ix_monitoring_events_event_type'), table_name='events', schema='monitoring')
    op.drop_table('events', schema='monitoring')
    op.drop_table('memory_profiles', schema='memory')
    op.drop_table('mcp_servers', schema='mcp')
    op.drop_table('installations', schema='marketplace')
    op.drop_table('tags', schema='governance')
    op.drop_table('classifications', schema='governance')
    op.drop_table('business_glossaries', schema='governance')
    op.drop_index(op.f('ix_datasource_datasources_workspace_id'), table_name='datasources', schema='datasource')
    op.drop_table('datasources', schema='datasource')
    op.drop_table('context_profiles', schema='context')
    op.drop_table('context_policies', schema='context')
    op.drop_table('connector_configs', schema='connector')
    op.drop_table('audit_events', schema='common')
    op.drop_table('catalogs', schema='catalog')
    op.drop_table('usage_metrics', schema='billing')
    op.drop_table('licenses', schema='billing')
    op.drop_table('invoices', schema='billing')
    op.drop_index(op.f('ix_ai_prompt_templates_name'), table_name='prompt_templates', schema='ai')
    op.drop_table('prompt_templates', schema='ai')
    op.drop_table('tools', schema='agent')
    op.drop_table('skills', schema='agent')
    op.drop_index(op.f('ix_agent_agents_name'), table_name='agents', schema='agent')
    op.drop_table('agents', schema='agent')
    op.drop_index(op.f('ix_workspace_workspaces_tenant_id'), table_name='workspaces', schema='workspace')
    op.drop_table('workspaces', schema='workspace')
    op.drop_index(op.f('ix_marketplace_items_item_type'), table_name='items', schema='marketplace')
    op.drop_table('items', schema='marketplace')
    op.drop_index(op.f('ix_billing_subscriptions_tenant_id'), table_name='subscriptions', schema='billing')
    op.drop_table('subscriptions', schema='billing')
    op.drop_table('search_history', schema='search')
    op.drop_table('saved_searches', schema='search')
    op.drop_table('sdk_downloads', schema='sdk')
    op.drop_table('metadata_versions', schema='lineage')
    op.drop_table('tenants', schema='identity')
    op.drop_table('role_permissions', schema='identity')
    op.drop_table('role_assignments', schema='identity')
    op.drop_table('owners', schema='governance')
    op.drop_index(op.f('ix_system_system_health_component_name'), table_name='system_health', schema='system')
    op.drop_table('system_health', schema='system')
    op.drop_index(op.f('ix_system_billing_events_tenant_id'), table_name='billing_events', schema='system')
    op.drop_index(op.f('ix_system_billing_events_metric'), table_name='billing_events', schema='system')
    op.drop_index(op.f('ix_system_billing_events_id'), table_name='billing_events', schema='system')
    op.drop_table('billing_events', schema='system')
    op.drop_index(op.f('ix_system_audit_logs_tenant_id'), table_name='audit_logs', schema='system')
    op.drop_index(op.f('ix_system_audit_logs_id'), table_name='audit_logs', schema='system')
    op.drop_table('audit_logs', schema='system')
    op.drop_index(op.f('ix_system_api_keys_tenant_id'), table_name='api_keys', schema='system')
    op.drop_index(op.f('ix_system_api_keys_id'), table_name='api_keys', schema='system')
    op.drop_table('api_keys', schema='system')
    op.drop_table('sdk_releases', schema='sdk')
    op.drop_table('provider_types', schema='provider')
    op.drop_table('traces', schema='monitoring')
    op.drop_table('categories', schema='marketplace')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_table('roles', schema='identity')
    op.drop_table('permissions', schema='identity')
    op.drop_table('organizations', schema='identity')
    op.drop_table('datasource_types', schema='datasource')
    op.drop_table('connector_types', schema='connector')
    op.drop_table('status_types', schema='common')
    op.drop_table('severity_levels', schema='common')
    op.drop_table('environments', schema='common')
    op.drop_table('plans', schema='billing')
    # ### end Alembic commands ###
