import React from 'react';

export default function AISummary() {
  return (
    <div className="dashboard-content">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1>AI Summary</h1>
          <p>LLM-generated synopsis of ctx_9f8a2.</p>
        </div>
        <button className="btn btn-secondary" style={{ padding: '10px 16px' }}>Regenerate</button>
      </div>

      <div className="widget" style={{ padding: '32px', background: 'linear-gradient(145deg, rgba(23,23,23,0.8), rgba(124, 58, 237, 0.05))', border: '1px solid rgba(124, 58, 237, 0.2)' }}>
        <div style={{ display: 'flex', alignItems: 'center', marginBottom: '24px' }}>
          <span style={{ fontSize: '24px', marginRight: '12px' }}>✨</span>
          <h2 style={{ fontSize: '18px', margin: 0 }}>Generated by GPT-4o</h2>
        </div>
        <p style={{ color: 'var(--text-secondary)', fontSize: '15px', lineHeight: '1.8' }}>
          This Pull Request introduces a fix for a known race condition within the AuthProvider component. It specifically targets an issue where simultaneous mounting of components would cause the token refresh mechanism to fire multiple times unnecessarily. The author (dev_jane) implemented a memoized callback and a debounce on the login form submission to resolve this behavior, effectively preventing duplicate authentication requests across the frontend client.
        </p>
      </div>
    </div>
  );
}
