apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencontextplatform.fullname" . }}
  labels:
    {{- include "opencontextplatform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opencontextplatform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opencontextplatform.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "opencontext"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
